- src/SingleGaussianPsf.cc
Fixed typo.
Couldn't create branch with lsst/meas_algorithms, so couldn't run a buildbot.
> Fixes 'dimensiosn' typo in schema field name.

- python/lsst/meas/algorithms/loadReferenceObjects.py
- tests/testLoadReferenceObjects.py
LoadReferenceObjectsTask enhancements:
- Added a new abstract method loadSkyCircle
- Renamed loadObjectsInBBox to loadPixelBox (to focus on sky vs pixel space)
- Provided a default implementation of loadPixelBox that calls loadSkyCircle
Updated tests/testLoadReferenceObjects.py accordingly
> Add loadSkyCircle abstract method to LoadReferenceObjectsTask

- python/lsst/meas/algorithms/objectSizeStarSelector.py
Previously, when attempted to take the median position of a list of points we
relied on the (old, pre-1.10) NumPy behaviour of providing NaN as the median
of an empty array. Newer NumPy will raise an ImportError instead. Here, we
explicitly check that we have at least one point before taking the median.
> Only take median position when points exist.

- python/lsst/meas/algorithms/loadReferenceObjects.py
Reference catalog loaders will frequently need butlers.
This allows subclasses to optionally take a butler.
> Allow butlers in subclasses

- python/lsst/meas/algorithms/__init__.py
- python/lsst/meas/algorithms/astrometrySourceSelector.py
- python/lsst/meas/algorithms/sourceSelector.py
- tests/testAstrometrySourceSelector.py
This is the first non-PSF source selector, with a new base class for other such things. It was lifted from measOptimisticB for use by jointcal.
> Added initial astrometry source selector, base class and tests.

- python/lsst/meas/algorithms/astrometrySourceSelector.py
Would be ~500x faster if we didn't have to do the footprint loop.
The if branch between vector and non-vectorized versions (and associated split in code logic) is unpleasant, but we'll have to live with it until we finalize the discussion here: https://community.lsst.org/t/memory-contiguity-and-python-execution-speed/884/12
> Added 100x faster vectorized version

- python/lsst/meas/algorithms/measureApCorr.py
- tests/testMeasureApCorr.py
Some measurement algorithms may always fail to produce a result on
certain data (e.g., seeing is too good or too bad to make the desired
measurement). The failure to measure an aperture correction for such
a measurement algorithm should not cause an exception. We now allow
certain pre-specified measurement algorithms (through the new config
parameter 'allowFailure') to fail and produce a warning rather than
an exception.
> make aperture correction failures optionally non-fatal

- src/CoaddPsf.cc
This adds support for reading very old Exposures with CoaddPsfs written before 7/10/2013.  It will not in general preserve the PSF's "average position" exactly, which is used when no position is provided to the PSF, because the information needed to reconstruct that has already been lost.
> meas_algorithms/DM-8147: Add backwards compatibility to CoaddPsf input.

- tests/testSdssShapePsf.py
This test is being added here in meas_algorithms rather than meas_base
(where SdssShape lives) due to the need to apply a spatially varying
psf model such that the psf is different at each position in the image.
This varying psf model is built with meas_algorithms' PcaPsf (which is
not accessible from meas_base).
> Review for DM-8714: Add unittest for base_SdssShape_psf measurement

- python/lsst/meas/algorithms/__init__.py
- python/lsst/meas/algorithms/matcherSourceSelector.py
- tests/testMatcherSourceSelector.py
Implemented new matcherSourceSelctor for use in meas_astrom with matchOptimisticB.
> Tickets/DM-8645: Implement new matcherSourceSelector object for use in matchOptimisticB code

- python/lsst/meas/algorithms/algorithmsLib.py
Changes are to let `Defect` be imported without needing other imports first.
> DM-8461: Wrap pipe_tasks with pybind11

- python/lsst/meas/algorithms/matcherSourceSelector.py
- tests/testMatcherSourceSelector.py
Changed isMultiple test to isParent. Removed test requirements for the variable nChild.
This corrects a bug introduced in DM-6824 and DM-8645 that decreased the AM1 performance in validate_drp using CHFT data. This returns the code back to it's previous performance.
> Tickets/DM-9120: matcherSourceSelector incorrectly uses nChild and footprints in isMultiple test.

- python/lsst/meas/algorithms/detection.py
As per the Jira discussion of DM-903, add this flag only if a schema is provided and thresholdPolarity=="both"
> Modify detection task so that flags.negative is only created if needed

- include/lsst/meas/algorithms/ExposurePatch.h
- include/lsst/meas/algorithms/SpatialModelPsf.h
- src/CR.cc
- src/ImagePca.cc
- src/Interp.cc
- src/PsfAttributes.cc
- src/PsfCandidate.cc
- src/SpatialModelPsf.cc
- tests/testPsfAttributes.cc
[DM-4639](https://jira.lsstcorp.org/browse/DM-4639) requires that `afw` components no longer have type members `Ptr` and `ConstPtr` representing shared pointers to those types. This is a breaking API change that requires changes to downstream code.
For clarity, no unnecessary changes changes were made to this package, not even a `clang-format` pass.
> DM-4639: modernize afw code and reduce doxygen errors

- include/lsst/meas/algorithms/CoaddBoundedField.h
- python/lsst/meas/algorithms/coaddBoundedField.cc
- src/CoaddBoundedField.cc
- tests/testCoaddBoundedField.py
These were added to the Boundedfield API as part of the work on PhotoCalib.
> DM-9192 add == and toString for new BoundedField API

- include/lsst/meas/algorithms/CoaddPsf.h
- python/lsst/meas/algorithms/SConscript
- python/lsst/meas/algorithms/__init__.py
- python/lsst/meas/algorithms/coaddPsf/__init__.py
- python/lsst/meas/algorithms/coaddPsf/coaddPsf.cc
- python/lsst/meas/algorithms/coaddPsf/coaddPsfContinued.py
This allows simple configuration of CoaddPsf from python.
> DM-11338: CoaddPsf: add control class

- tests/testSdssShapePsf.py
The noise realization in the test data is dependent on the random
number generator.  Some tests can depend on the particular realization,
so we seed all dataset realizations explicitly.  The seed value is
chosen solely based on the "test passes" criterion.
> DM-11620: Make all test dataset realization deterministic

- src/CoaddPsf.cc
- tests/test_coaddPsf.py
A common problem when calling CoaddPsf.computePsfImage() is that
WarpedPsf.computeBBoxFromTransform throws a RangeError stating
'Unexpectedly large transform passed to WarpedPsf'. This is
usually because the astrometry for an input is poor, but it would
be nice to identify *which* input: so add the exposure ID to the
exception message.
> DM-11023: CoaddPsf: add more exception info

- python/lsst/meas/algorithms/astrometrySourceSelector.py
- python/lsst/meas/algorithms/matcherSourceSelector.py
- python/lsst/meas/algorithms/measureApCorr.py
- python/lsst/meas/algorithms/objectSizeStarSelector.py
- python/lsst/meas/algorithms/sourceSelector.py
/software/lsstsw/stack/Linux64/meas_algorithms/13.0-18-gc4ad422+4/python/lsst/meas/algorithms/objectSizeStarSelector.py:400: RuntimeWarning: invalid value encountered in less
bad = numpy.logical_or(bad, width < self.config.widthMin)
/software/lsstsw/stack/Linux64/meas_algorithms/13.0-18-gc4ad422+4/python/lsst/meas/algorithms/objectSizeStarSelector.py:401: RuntimeWarning: invalid value encountered in greater
bad = numpy.logical_or(bad, width > self.config.widthMax)
/software/lsstsw/stack/Linux64/meas_algorithms/13.0-18-gc4ad422+4/python/lsst/meas/algorithms/matcherSourceSelector.py:126: RuntimeWarning: invalid value encountered in greater
return sourceCat.get(self.fluxKey)/sourceCat.get(self.fluxSigmaKey) > self.config.minSnr
> DM-11776: suppress numpy NAN warnings

- python/lsst/meas/algorithms/detection.py
- tests/test_detection.py
We weren't restoring the original image because we didn't have a copy
of it.
> DM-13617: detection: fix restoration of tempWideBackground

- python/lsst/meas/algorithms/dynamicDetection.py
- tests/test_dynamicDetection.py
Makes the minimum number of sources for statistics configurable,
avoiding obscure numpy errors from having zero sources.
> DM-13517: dynamicDetection: require sufficient sources for statistics

- include/lsst/meas/algorithms/CoaddBoundedField.h
- include/lsst/meas/algorithms/CoaddPsf.h
- include/lsst/meas/algorithms/DoubleGaussianPsf.h
- include/lsst/meas/algorithms/KernelPsf.h
- include/lsst/meas/algorithms/SingleGaussianPsf.h
- src/CoaddTransmissionCurve.cc
- src/KernelPsf.cc
lsst/afw#366 adds a `noexcept` specifier to `afw::table::io::Persistence::isPersistable`. This PR adds a `noexcept` specifier to all methods that override `Persistence::isPersistable`, as required by type safety.
> DM-9937: Add noexcept specifiers to applicable methods in afw

- tests/test_measure.py
This test was disabled on DM-1608, when we inadvertently dropped the call to
FootprintSet.makeSources(). Here, we restore that, and fix up the rest of the
code to run successfully.
> DM-17399: Restore broken test.

- python/lsst/meas/algorithms/dynamicDetection.py
tweakBackground() is called twice during DynamicDetection, but the first
call does not affect footprint detection because it only tweaks the
original image [A] and forgets to modify the PSF-convoluted image [B] on
which the detection process runs. In peak detection, a small-scale
background is estimated from [A] and subtracted from [B]. It is wrong
because [A] and [B] has different biases due to the first call to
tweakBackground().
It is better to cease to call tweakBackground() here than to tweak [B]
together with [A]. The background estimate at this point is wrong because
detection masks have been shrinked by tempWideBackground.
> DM-17413: Don't do the first tweakBackground() during DynamicDetection.

- python/lsst/meas/algorithms/defects.py
- tests/test_interp.py
Now use ECSV format so that we can store metadata in the text files.
> DM-19627: Update text format for writing defects

- tests/test_psfDetermination.py
The original complaint in the ticket was already satisfied, but it turned out there were a few other things that needed to be fixed up with this. And then I added minimal testing for both showPsfMosaic and showPsf.
> DM-2891: Fixing showPsfMosaic and adding some tests

- python/lsst/meas/algorithms/readFitsCatalogTask.py
- tests/test_readFitsCatalog.py
This also includes fixing the unit tests.
Using astropy.table.Table also solves issues dealing with endianness of values coming from FITS files.
> DM-18036: Use Tables to read FITS

- bin.src/check_ingested_reference_catalog.py
- doc/lsst.meas.algorithms/creating-a-reference-catalog.rst
The gaia epochs were TCB, not UTC.
This also takes longer to ingest, as the astropy time conversion for
TCB->UTC TAI is ~3-5x slower than that of UTC->UTC TAI.
> DM-22027: Re-make Gaia refcat to fix epoch

- python/lsst/meas/algorithms/simple_curve.py
- tests/test_curve.py
The default was to raise an error if interpolating outside the bounds of the curve.  The default now is to clamp to 0. outside the range of the curve.
> DM-23077: Change default behavior for interpolate

- python/lsst/meas/algorithms/defects.py
Now assign whole rows rather than assigning elements
in a loop.
> DM-24060: Improve table creation inside Defects

- src/CR.cc
- src/SpatialModelPsf.cc
This PR replaces calls to `Kernel.getCtrX` and `getCtrY` with `getCtr`, and calls to `setCtrX` and `setCtrY` with `setCtr`.
> DM-23651: ap_pipe calls some deprecated things

- include/lsst/meas/algorithms/python.h
- python/lsst/meas/algorithms/imagePsf.cc
- tests/test_imagePsf_trampoline.py
The trampoline class enables subclasses of lsst.meas.algorithms.ImagePsf
to be created in python.
> DM-25373 Add ImagePsf trampoline

- python/lsst/meas/algorithms/ingestIndexManager.py
- tests/SConscript
- tests/ingestIndexTestBase.py
- tests/nopytest_ingestIndexReferenceCatalog.py
- tests/test_htmIndex.py
AKA “that looks more fun than proof rereading slides”.
> DM-25979: IngestIndexReferenceTask throws if coord_err_unit is None

- python/lsst/meas/algorithms/brightStarStamps.py
- tests/test_brightStarStamps.py
One of 3 PRs for [DM-24830](https://jira.lsstcorp.org/browse/DM-24830) (the other two being obs_base and obs_subaru).
This is the main one, and contains both the class itself, and a few tests.
Jenkins run [#31959](https://ci.lsst.codes/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/31959/pipeline)
> DM-24830: Create dataset class for processed bright star stamps

- python/lsst/meas/algorithms/defects.py
- tests/test_interp.py
This allows us to control whether the defects are normalized when being read from an external source. We default to False.
> DM-27045: Add normalize_on_init to readText and readFits

- python/lsst/meas/algorithms/ingestIndexManager.py
Fixes python 3.8 multiprocessing start method of `spawn` on macOS.
> DM-27364: Initialize counter before forking for python 3.8 support on mac

- python/lsst/meas/algorithms/brightStarStamps.py
- tests/test_brightStarStamps.py
One of 5 PRs for [DM-25304](https://jira.lsstcorp.org/browse/DM-25304).
This makes the computation of annularFlux and normalization of bright star stamps a BrightStarStamp method.
> DM-25304: Add task to extract and process bright stars

- python/lsst/meas/algorithms/stamps.py
- tests/test_stamps.py
One of four PRs for [DM-28717](https://jira.lsstcorp.org/browse/DM-28717), the others being afw, obs_base and daf_butler.
> DM-28717: Allow for Stamps formatter to handle bbox

- ups/meas_algorithms.build
- ups/meas_algorithms.cfg
This PR fixes a build error caused by converting `pipe_base` to a pure-Python package in lsst/pipe_base#184.
> DM-23330: Doxygen warnings in pipe_base

- python/lsst/meas/algorithms/brightStarStamps.py
- python/lsst/meas/algorithms/stamps.py
- tests/test_stamps.py
[Jira ticket](https://jira.lsstcorp.org/browse/DM-30445)
[Jenkins run 34358](https://ci.lsst.codes/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/34358/pipeline)
> DM-30445: Add optional Archive element to stamps

- python/lsst/meas/algorithms/brightStarStamps.py
[Jira ticket](https://jira.lsstcorp.org/browse/DM-30733)
> DM-30733: Make BrightStarStamps.initAndNormalize catch RuntimeExceptions

- COPYRIGHT
- include/lsst/meas/algorithms/WarpedPsf.h
- python/lsst/meas/algorithms/warpedPsf.cc
- src/WarpedPsf.cc
- tests/test_warpedPsf.cc
This PR implements persistence for `WarpedPsf`. The adopted persisted form is merely the concatenation of the three subobjects currently making up the `WarpedPsf` implementation, as I don't see a more generic way to represent that state. Depends on lsst/afw#597.
> DM-30829: Add persistence for WarpedPsf

- python/lsst/meas/algorithms/brightStarStamps.py
- tests/test_brightStarStamps.py
One of two PRs for DM-26651, [the other](https://github.com/lsst/pipe_tasks/pull/546) being in pipe_tasks.
[Jira ticket](https://jira.lsstcorp.org/browse/DM-26651)
[Jenkins run](https://ci.lsst.codes/blue/organizations/jenkins/stack-os-matrix/detail/stack-os-matrix/34567/pipeline)
> DM-26651: Change BrightStarStamp to save archive elements, positions, and number of rotations

- python/lsst/meas/algorithms/detection.py
- python/lsst/meas/algorithms/pcaPsfDeterminer.py
This works more generally for a broader range of metadata objects.
> DM-32682: Use metadata[]= rather than metadata.set()

- tests/test_cr.py
`logUtils.traceSetAt` is now called by `trace_set_at` so there is no need to call the `lsst.log` version directly.
Requires lsst/utils#108
> DM-32679: Use lsst.utils.logging trace_set_at

- python/lsst/meas/algorithms/ingestIndexReferenceTask.py
- python/lsst/meas/algorithms/loadIndexedReferenceObjects.py
- python/lsst/meas/algorithms/loadReferenceObjects.py
- tests/nopytest_ingestIndexReferenceCatalog.py
- tests/test_loadReferenceObjects.py
As part of getting the gen3 code to support the more complicated filter mapping logic that the gen2 code did, I also refactored several methods into the common base class. Gen2 is going away soon, but we also want to keep as much of the gen2 test coverage as we can: this should help with that.
> DM-27843: Add anyFilterMapsToThis support to ReferenceObjectLoader

- src/WarpedPsf.cc
Previous logic forced the image size to be odd, but picked the center of the kernel image bbox based on center of the transformed kernel image bbox.  But the output kernel image center is an input: (0, 0).
This manifested as even-sizes images later in CoaddPsf; the union of two odd-sized boxes with the same dimensions but offset center is an even-sized box.
> DM-35105 Force (0, 0) for center of warped PSF images.

- src/CR.cc
- src/SpatialModelPsf.cc
This PR removes or rearranges Doxygen comments that were intended to be file-level (or, in one case, block-level) but instead described namespaces.
> DM-22823: Remove accidental Doxygen comments for namespaces

- doc/lsst.meas.algorithms/tasks/lsst.meas.algorithms.SourceDetectionTask.rst
- python/lsst/meas/algorithms/detection.py
The fact that we're always convolving with a Gaussian needs to be more obvious in the task docs.
> u/parejkoj: Add source detection task doc paragraph

- python/lsst/meas/algorithms/measureApCorr.py
- tests/test_measureApCorr.py
This replaces the default source selector to use all possible (unflagged) stars, and additional checks on the fit degree after outlier rejection.
> DM-37955: Update measureApCorrTask to use robust median outlier rejection.

- python/lsst/meas/algorithms/skyObjects.py
- tests/test_dynamicDetection.py
This commit switches sky object placement from pseudo-random to quasi-random positioning using the Halton Sequence. During testing, the dynamic detection task unit test returned failures for all tests which employ sky objects. This is believed to be an inherent weakness within the dynamic detection task highlighted by the changes made on this ticket, and not related to any of the changes made here. As a consequence, the relative tolerance for acceptance of those failing unit tests was increased from 0.1 to 0.15 in order to allow this ticket to pass at this time.
> DM-23781-v25: Improve Sky Object Placement

- python/lsst/meas/algorithms/detection.py
This PR overrides the global default from DM-38246 because it was harming several metrics.
> DM-39306: Change excludeMaskPlanes to not exclude any by default.

- python/lsst/meas/algorithms/astrometrySourceSelector.py
- python/lsst/meas/algorithms/flaggedSourceSelector.py
- python/lsst/meas/algorithms/matcherSourceSelector.py
- python/lsst/meas/algorithms/objectSizeStarSelector.py
- python/lsst/meas/algorithms/sourceSelector.py
'get' actually invokes the ColumnView method via __getattr__ forwarding, and that's less capable than Catalog.__getitem__ as well as being a pointless forward to ColumnView.__getitem__ that probably never needed to exist.
> DM-39828: Use 'Catalog.__getitem__' instead of 'get' in selectors.

- doc/lsst.meas.algorithms/creating-a-reference-catalog.rst
A quick update to the refcat docs to refer people to the correct location for the htm7 index files on USDF. No one ever needs to generate their own for our existing refcats.
> Update docs to refer to location on USDF

- tests/test_psfCandidate.py
Other tests running could change this state and break the test.
> DM-41846: Force psf candidate state before testing stringification

- doc/lsst.meas.algorithms/tasks/lsst.meas.algorithms.NormalizedCalibrationFluxTask.rst
- python/lsst/meas/algorithms/__init__.py
- python/lsst/meas/algorithms/measureApCorr.py
- python/lsst/meas/algorithms/normalizedCalibrationFlux.py
- tests/test_normalizedCalibrationFlux.py
Along with the new NormalizedCompensatedFluxTask (to normalize compensated tophats and gaussians) this adds a new "median shift" to the aperture corrections that helps reduce scatter in wide field images.
> DM-38632: Add NormalizedCompensatedFluxTask and update aperture corrections.

- python/lsst/meas/algorithms/normalizedCalibrationFlux.py
- tests/test_normalizedCalibrationFlux.py
This will make the routine always succeed in creating calibration fluxes, falling back to an identity transformation if one isn't available.  (This is similar to the regular aperture corrections that leave uncorrected values in place).
> DM-45002: Warn instead of raising with incomplete normalization aperture correction.

- ups/meas_algorithms.table
Needed to be able to use the generic fits formatter.
> DM-45468: Add obs_base dependency

- python/lsst/meas/algorithms/__init__.py
- python/lsst/meas/algorithms/gp_interpolation.py
- python/lsst/meas/algorithms/interp.cc
- python/lsst/meas/algorithms/interp.py
- python/lsst/meas/algorithms/reinterpolate_pixels.py
- tests/test_gp_interp.py
See this ticket --> https://rubinobs.atlassian.net/browse/DM-44305
> DM-44305: Implement Gaussian Process interpolation over bad pixels

- python/lsst/meas/algorithms/loadReferenceObjects.py
Moved version check to later and only conduct version check if fluxField has no units or incorrect units
> DM-46486: added check for units of flux field

- python/lsst/meas/algorithms/gp_interpolation.py
- tests/test_gp_interp.py
See here: https://rubinobs.atlassian.net/browse/DM-46710
> DM-46710: Disable jax in Gaussian process interp

- python/lsst/meas/algorithms/computeExPsf.py
- python/lsst/meas/algorithms/treecorrUtils.py
- tests/test_computeExPsf.py
See https://rubinobs.atlassian.net/browse/DM-45899 for more informations.
> DM-45899: Write a Task to compute Ex for TEx

- python/lsst/meas/algorithms/stamps.py
Raw guider images have additional tables that can not be read but should be ignored to allow the rest of the data to be read.
> DM-43620: When reading stamps, ignore non-image binary tables

- python/lsst/meas/algorithms/detection.py
In principle, convolution-induced mask growth may block some good sources near zeroed-out regions, so we switched to the original masked regions. Unfortunately in practice, bogus diaSources appeared near masked regions, so we are undoing this change and  living with losing some edge-y diaSources.
> DM-47385: Refine mask exclusion behavior in removeBadPixels (aka cancel original masks)

- python/lsst/meas/algorithms/testUtils.py
- tests/convertReferenceCatalogTestBase.py
- tests/nopytest_convertReferenceCatalog.py
- tests/test_accumulator_mean_stack.py
- tests/test_brightStarStamps.py
- tests/test_cloughTocher2DInterpolate.py
- tests/test_coaddBoundedField.py
- tests/test_computeExPsf.py
- tests/test_convertReferenceCatalog.py
- tests/test_dynamicDetection.py
- tests/test_gp_interp.py
- tests/test_interp.py
- tests/test_measureApCorr.py
- tests/test_normalizedCalibrationFlux.py
- tests/test_objectSizeStarSelector.py
- tests/test_psfSelectTest.py
- tests/test_stamps.py
- tests/test_variance.py
@PFLeget there is a problem with numpy 2 and test_computeExPsf.py. The problem seems to be that `multivariate_normal` is returning very different answers between numpy 1 and 2. The inputs seem to be the same. Also, using the modern RNG APIs leads to breakage even on numpy 1.
> DM-45545: Fixes for numpy 2

- python/lsst/meas/algorithms/detection.py
- python/lsst/meas/algorithms/dynamicDetection.py
- python/lsst/meas/algorithms/subtractBackground.py
- tests/test_detection.py
- tests/test_subtractBackground.py
This PR also adds some unit tests for SubtractBackgroundTask and the background re-estimation in SourceDetectionTask.
> DM-48783: Add illumination correction support to SubtractBackgroundTask and SourceDetectionTask

- python/lsst/meas/algorithms/subtractBackground.py
This  change is to distinguish background subtraction errors in detection when we don't expect them to succeed because all of the exposure pixels are masked.
> DM-48718: raise 'NoWorkFound' in SubtractBackgroundTask when all pixels are masked

- src/CR.cc
The second assert loop, if run on a bad image, would take 10 minutes before telling you things were bad.
> DM-50880: Remove cosmic ray assert loops that can take an extremely long time.

- python/lsst/meas/algorithms/loadReferenceObjects.py
Turns out for dense fields half the refcat loading time is due to non-vectorized filtering.
> DM-51053: Switch to vectorized refcat filtering

- python/lsst/meas/algorithms/subtractBackground.py
The function `scipy.ndimage.median_filter` that is used for the filtering has undefined behavior when NaN values are present. These should all be masked, but interpolation can lead to pixels near the masked regions being affected.
> DM-51361: Catch NaN values when using background filtering.
